require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "Workspace", type: :request do
  let(:user_without_workspace) { create(:user, workspace: nil, role: nil) }
  let(:user_with_workspace) { create(:user, workspace: create(:workspace), role: :admin) }

  context "when user has no workspace" do
    before { sign_in user_without_workspace }

    describe "GET /workspace/new" do
      it "renders the new workspace view" do
        get new_workspace_path
        expect(response).to have_http_status(:ok)
      end
    end

    describe "POST /workspace" do
      it "creates a new workspace and assign it to the user" do
        post workspace_path, params: { workspace: { name: "Org", subdomain: "myorg" } }

        workspace = Workspace.last
        user_without_workspace.reload

        expect(workspace).to be_present
        expect(user_without_workspace.workspace).to eq(workspace)
        expect(response).to redirect_to(app_root_path(workspace.subdomain))
      end

      it "update user role to be admin" do
        post workspace_path, params: { workspace: { name: "Org", subdomain: "myorg" } }

        user_without_workspace.reload

        expect(user_without_workspace.role).to eq("admin")
      end
    end
  end

  context "when user has a workspace" do
    before { sign_in user_with_workspace }

    describe "GET /workspace/new" do
      it "redirects to the app view" do
        get new_workspace_path
        expect(response).to redirect_to(app_root_path(user_with_workspace.workspace.subdomain))
      end
    end
  end
end
