require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/app/articles", type: :request do
  let(:workspace) { create(:workspace) }
  let(:admin) { create(:user, workspace: workspace, role: :admin) }

  before { sign_in admin }

  it "create a new article with status draft and creator admin" do
    expect {
      post app_articles_path(workspace.subdomain)
    }.to change(Article, :count).by(1)

    new_article = Article.last
    expect(response).to redirect_to(edit_app_article_path(new_article))
    follow_redirect!

    expect(response.body).to include("Article was successfully created.")
    expect(response).to render_template(:edit)
  end
end
